version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.25.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 1337:9090
    networks:
      - jvm-monitoring

  grafana:
    image: grafana/grafana:7.4.2
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
    ports:
      - 1338:3000
    depends_on:
      - prometheus
    networks:
      - jvm-monitoring

networks:
  jvm-monitoring:
