global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'remote-jvm'

scrape_configs:
  - job_name: 'remote-jvm'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus

    static_configs:
      - targets: [ '172.17.0.1:9000' ]
